project:
  type: website
  output-dir: docs

format:
  html:
    theme: simplex     # 🎨 Simplex 테마 적용
    css: styles.css     # 🧾 사용자 줄간격 CSS 연결

website:
  title: "영화 다양성 분석"
  navbar:
    left:
      - href: index.qmd
        text: 서론
      - href: genre.qmd
        text: 장르와 다양성
      - href: director.qmd
        text: 감독 성별과 다양성
      - href: character.qmd
        text: 등장인물과 다양성
      - href: conclusion.qmd
        text: 결론
